batch_0:
	CUDA_VISIBLE_DEVICES=0 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=aerial-pool training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=0 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=asbestos training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=0 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=bone-fracture-7fylg training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=0 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=cavity-rs0uf training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=0 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=document-parts training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=0 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=farcry6-videogame training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=0 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=furniture-ngpea training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=0 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=grass-weeds training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=0 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=parasites-1s07h training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=0 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=radio-signal training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=0 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=road-signs-6ih4y training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=0 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=sedimentary-features-9eosf training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=0 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=soda-bottles training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9

batch_1:
	CUDA_VISIBLE_DEVICES=1 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=activity-diagrams-qdobr training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=1 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=cable-damage training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=1 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=cells-uyemf training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=1 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=csgo-videogame training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=1 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=currency-v4f8j training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=1 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=flir-camera-objects training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=1 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=gauge-u2lwv training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=1 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=leaf-disease-nsdsr training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=1 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=secondary-chains training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=1 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=street-work training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=1 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=thermal-cheetah-my4dp training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=1 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=truck-movement training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=1 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=underwater-pipes-4ng4t training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9

batch_2:
	CUDA_VISIBLE_DEVICES=2 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=4-fold-defect training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=2 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=aerial-spheres training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=2 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=animals-ij5d2 training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=2 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=aquarium-qlnqy training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=2 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=avatar-recognition-nuexe training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=2 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=construction-safety-gsnvb training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=2 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=hand-gestures-jps7z training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=2 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=marbles training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=2 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=sign-language-sokdr training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=2 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=signatures-xc8up training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=2 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=trail-camera training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=2 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=wine-labels training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=2 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=x-ray-rheumatology training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9

batch_3:
	CUDA_VISIBLE_DEVICES=3 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=acl-x-ray training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=3 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=bacteria-ptywi training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=3 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=cell-towers training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=3 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=coins-1apki training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=3 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=digits-t2eg6 training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=3 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=halo-infinite-angel-videogame training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=3 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=paper-parts training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=3 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=peixos-fish training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=3 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=pills-sxdht training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=3 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=road-traffic training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=3 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=smoke-uvylj training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=3 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=soccer-players-5fuqs training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=3 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=valentines-chocolate training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9

batch_4:
	CUDA_VISIBLE_DEVICES=4 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=abdomen-mri training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=4 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=apples-fvpl5 training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=4 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=cotton-plant-disease training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=4 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=fish-market-ggjso training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=4 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=poker-cards-cxcvz training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=4 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=tabular-data-wf9uh training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=4 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=team-fight-tactics training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=4 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=underwater-objects-5v7p8 training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=4 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=vehicles-q0x2v training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=4 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=wall-damage training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=4 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=washroom-rf1fa training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=4 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=weed-crop-aerial training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9

batch_5:
	CUDA_VISIBLE_DEVICES=5 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=aerial-cows training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=5 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=axial-mri training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=5 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=circuit-elements training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=5 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=coral-lwptl training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=5 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=corrosion-bi3q3 training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=5 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=lettuce-pallets training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=5 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=mitosis-gjs3g training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=5 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=number-ops training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=5 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=paragraphs-co84b training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=5 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=peanuts-sd4kf training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=5 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=people-in-paintings training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=5 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=robomasters-285km training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9

batch_6:
	CUDA_VISIBLE_DEVICES=6 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=circuit-voltages training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=6 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=cloud-types training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=6 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=excavators-czvg9 training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=6 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=gynecology-mri training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=6 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=insects-mytwu training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=6 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=mask-wearing-608pr training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=6 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=phages training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=6 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=printed-circuit-board training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=6 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=shark-teeth-5atku training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=6 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=stomata-cells training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=6 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=thermal-dogs-and-people-x6ejw training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=6 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=tweeter-posts training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9

batch_7:
	CUDA_VISIBLE_DEVICES=7 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=apex-videogame training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=7 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=bccd-ouzjz training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=7 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=bees-jt5in training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=7 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=brain-tumor-m2pbp training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=7 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=cables-nl42k training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=7 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=chess-pieces-mjzgj training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=7 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=cotton-20xz5 training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=7 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=liver-disease training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=7 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=pests-2xlvx training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=7 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=solar-panels-taxvb training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=7 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=tweeter-profile training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
	CUDA_VISIBLE_DEVICES=7 python -m super_gradients.train_from_recipe --config-name=roboflow_deciyolo_s dataset_name=uno-deck training_hyperparams.initial_lr=0.0001 training_hyperparams.optimizer_params.weight_decay=0.0001 training_hyperparams.zero_weight_decay_on_bias_and_bn=True training_hyperparams.ema=True training_hyperparams.ema_params.decay=0.9
