## Super-Gradients configuration for black/mypy/isort etc tools.

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = True
force_grid_wrap = 0
use_parentheses = True
ensure_newline_before_comments = True
line_length = 119

## Configuration for Black.
[tool.black]
line-length = 119
target-version = ['py36', 'py37', 'py38', 'py39' ]
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.circleci
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
