source_ckpt_folder_name: # dirname for checkpoint loading
strict_load: # key matching strictness for loading checkpoint's weights
  _target_: super_gradients.training.sg_model.StrictLoad
  value: True
sync_bn: False # whether to convert bn to sync.bn
load_checkpoint: False # whether to load checkpoint
load_backbone: False # whether to load only backbone part of checkpoint
external_checkpoint_path: # checkpoint path that is not located in super_gradients/checkpoints


