defaults:
  - yolo_arch_params

anchors:
  _target_: super_gradients.training.utils.detection_utils.Anchors
  anchors_list: [[], [], []]
  strides: [8, 16, 32]

yolo_type: 'yoloX'

depth_mult_factor: 0.33
width_mult_factor: 0.375