defaults:
  - cityscapes_dataset_params
  - _self_

train_dataset_params:
  transforms:
    # for more options see common.factories.transforms_factory.py
    - ColorJitterSeg:
        brightness: 0.1
        contrast: 0.1
        saturation: 0.1

    - RandomFlipSeg:
        prob: 0.5

    - RandomRescaleSeg:
        scales: [ 0.4, 1.6 ]

    - PadShortToCropSizeSeg:
        crop_size: 1024
        fill_image: [ 19, 0, 0 ]
        fill_mask: 19                     # ignored label idx

    - CropImageAndMaskSeg:
        crop_size: 1024
        mode: random

train_dataloader_params:
  batch_size: 4

val_dataloader_params:
  batch_size: 4
