defaults:
  - cityscapes_dataset_params
  - _self_

train_dataset_params:
  transforms:
    - ColorJitterSeg:
        brightness: 0.5
        contrast: 0.5
        saturation: 0.5

    - RandomFlipSeg:
        prob: 0.5

    - RandomRescaleSeg:
        scales: [ 0.5, 2. ]

    - PadShortToCropSizeSeg:
        crop_size: [ 1024, 1024 ]
        fill_mask: 19

    - CropImageAndMaskSeg:
        crop_size: [ 1024, 1024 ]
        mode: random


train_dataloader_params:
  batch_size: 6

val_dataloader_params:
  batch_size: 6
