defaults:
  - cityscapes_dataset_params
  - _self_

train_dataset_params:
  transforms:
    # for more options see common.factories.transforms_factory.py
    - ColorJitterSeg:
        brightness: 0.5
        contrast: 0.5
        saturation: 0.5

    - RandomFlipSeg:
        prob: 0.5

    - RandomRescaleSeg:
        scales: [ 0.125, 1.5 ]

    - PadShortToCropSizeSeg:
        crop_size: [ 1024, 512 ]
        fill_mask: 19                  # ignored label idx

    - CropImageAndMaskSeg:
        crop_size: [ 1024, 512 ]
        mode: random

val_dataset_params:
  transforms:
    - RescaleSeg:
        scale_factor: 0.5

train_dataloader_params:
  batch_size: 16

val_dataloader_params:
  batch_size: 16
