train_dataset_params:
  - _target_: torch.Tensor
      _target_: numpy.zeros
        [5, 3, 32, 32]
  - _target_: torch.LongTensor
      _target_: numpy.zeros
        5

train_dataloader_params:
  batch_size: 5
