train_dataset_params:
  root_dir: /data/coco/
  images_dir: images/train2017
  json_file: annotations/person_keypoints_train2017.json
  include_empty_samples: False
  min_instance_area: 128

  transforms:
    - KeypointsLongestMaxSize:
        max_sizes: [ 640, 640 ]
        p: 1.0

    - KeypointsPadIfNeeded:
        output_size: [ 640, 640 ]
        image_pad_value: [ 127, 127, 127 ]
        mask_pad_value: 1

    - KeypointsRandomHorizontalFlip:
        # Note these indexes are COCO-specific. If you're using a different dataset, you'll need to change these accordingly.
        flip_index: [0, 2, 1, 4, 3, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15, 17]
        prob: 0.5

    - KeypointsRandomAffineTransform:
        input_size: [640, 640]
        output_size: [640, 640]
        max_rotation: 30
        min_scale: 0.75
        max_scale: 1.5
        scale_type: 'short'
        max_translate: 40
        image_pad_value: [127, 127, 127]
        mask_pad_value: 1

    - KeypointsToTensor:

    - KeypointsNormalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

  target_generator:
    DEKRTargetsGenerator:
      output_stride: 4
      sigma: 2
      center_sigma: 4
      bg_weight: 0.1
      offset_radius: 4

val_dataset_params:
  root_dir: /data/coco/
  images_dir: images/val2017
  json_file: annotations/person_keypoints_val2017.json
  include_empty_samples: True
  min_instance_area: 128
  transforms:
    - KeypointsLongestMaxSize:
        max_sizes: [ 640, 640 ]
        p: 1.0

    - KeypointsPadIfNeeded:
        output_size: [ 640, 640 ]
        image_pad_value: [ 127, 127, 127 ]
        mask_pad_value: 1

    - KeypointsToTensor:

    - KeypointsNormalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

  target_generator:
    DEKRTargetsGenerator:
      output_stride: 4
      sigma: 2
      center_sigma: 4
      bg_weight: 0.1
      offset_radius: 4

train_dataloader_params:
  shuffle: True
  batch_size: 8
  num_workers: 8
  drop_last: True
  collate_fn:
    _target_: super_gradients.training.datasets.pose_estimation_datasets.COCOKeypointsCollate

val_dataloader_params:
  batch_size: 24
  num_workers: 8
  drop_last: False
  collate_fn:
    _target_: super_gradients.training.datasets.pose_estimation_datasets.COCOKeypointsCollate
