num_joints: 17

# OKs sigma values take from https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py#L523
oks_sigmas: [0.026, 0.025, 0.025, 0.035, 0.035, 0.079, 0.079, 0.072, 0.072, 0.062, 0.062, 1.007, 1.007, 0.087, 0.087, 0.089, 0.089]

flip_indexes_heatmap: [ 0, 2, 1, 4, 3, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15, 17]
flip_indexes_offset: [ 0, 2, 1, 4, 3, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15,]

joint_links:
  - [0, 1]
  - [0, 2]
  - [1, 2]
  - [1, 3]
  - [2, 4]
  - [3, 5]
  - [4, 6]
  - [5, 6]
  - [5, 7]
  - [5, 11]
  - [6, 8]
  - [6, 12]
  - [7, 9]
  - [8, 10]
  - [11, 12]
  - [11, 13]
  - [12, 14]
  - [13, 15]
  - [14, 16]


train_dataset_params:
  data_dir: /data/coco # root path to coco data
  images_dir: images/train2017
  json_file: annotations/person_keypoints_train2017.json

  include_empty_samples: False
  min_instance_area: 64

  transforms:
    - KeypointsLongestMaxSize:
        max_height: 640
        max_width: 640

    - KeypointsPadIfNeeded:
        min_height: 640
        min_width: 640
        image_pad_value: [ 127, 127, 127 ]
        mask_pad_value: 1

    - KeypointsRandomHorizontalFlip:
        # Note these indexes are COCO-specific. If you're using a different dataset, you'll need to change these accordingly.
        flip_index: [ 0, 2, 1, 4, 3, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15 ]
        prob: 0.5

    - KeypointsRandomAffineTransform:
        max_rotation: 30
        min_scale: 0.5
        max_scale: 2
        max_translate: 0.2
        image_pad_value: [ 127, 127, 127 ]
        mask_pad_value: 1
        prob: 0.75

    - KeypointsImageToTensor

    - KeypointsImageNormalize:
        mean: [ 0.485, 0.456, 0.406 ]
        std: [ 0.229, 0.224, 0.225 ]


val_dataset_params:
  data_dir: /data/coco/

  images_dir: images/val2017
  json_file: annotations/person_keypoints_val2017.json
  include_empty_samples: True
  min_instance_area: 128
  transforms:
    - KeypointsLongestMaxSize:
        max_height: 640
        max_width: 640

    - KeypointsPadIfNeeded:
        min_height: 640
        min_width: 640
        image_pad_value: [ 127, 127, 127 ]
        mask_pad_value: 1

    - KeypointsImageToTensor

    - KeypointsImageNormalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]


train_dataloader_params:
  shuffle: True
  batch_size: 8
  num_workers: 8
  drop_last: True
  collate_fn:
    _target_: super_gradients.training.datasets.pose_estimation_datasets.KeypointsCollate

val_dataloader_params:
  batch_size: 24
  num_workers: 8
  drop_last: False
  collate_fn:
    _target_: super_gradients.training.datasets.pose_estimation_datasets.KeypointsCollate

_convert_: all
