data_dir: /data/coco # root path to coco data
train_subdir: images/train2017 # sub directory path of data_dir containing the train data.
val_subdir: images/val2017 # sub directory path of data_dir containing the validation data.
train_json_file: instances_train2017.json # path to coco train json file, data_dir/annotations/train_json_file.
val_json_file: instances_val2017.json # path to coco validation json file, data_dir/annotations/val_json_file.

batch_size: 16 # batch size for trainset
val_batch_size: 64 # batch size for valset
val_image_size: 640 # image size for valset
train_image_size: 640 # image size for trainset

# Augmentations
mixup_prob: 1.0 # probability to apply per-sample mixup
degrees: 10. # rotation degrees, randomly sampled from [-degrees, degrees]
shear: 2.0 # shear degrees, randomly sampled from [-degrees, degrees]
flip_prob: 0.5 # probability to apply horizontal flip
hsv_prob: 1.0 # probability to apply HSV transform
hgain: 5 # HSV transform hue gain (randomly sampled from [-hgain, hgain])
sgain: 30 # HSV transform saturation gain (randomly sampled from [-sgain, sgain])
vgain: 30 # HSV transform value gain (randomly sampled from [-vgain, vgain])
mosaic_scale: [0.1, 2] # random rescale range (keeps size by padding/cropping) after mosaic transform.
mixup_scale: [0.5, 1.5] # random rescale range for the additional sample in mixup
mosaic_prob: 1. # probability to apply mosaic
translate: 0.1 # image translation fraction

targets_format:
  _target_: super_gradients.training.utils.detection_utils.DetectionTargetsFormat # targets format
  value: LABEL_CXCYWH

with_crowd: False # whether to return "crowd" labels in validation

val_collate_fn: # collate function for valset
  _target_: super_gradients.training.utils.detection_utils.DetectionCollateFN


train_collate_fn: # collate function for trainset
  _target_: super_gradients.training.utils.detection_utils.DetectionCollateFN

cache_dir_path: # path to a directory that will be used for caching (with numpy.memmap).
cache_train_images: False
cache_val_images: False

_convert_: all