defaults:
  - coco_detection_yolox_dataset_params

batch_size: 32
val_batch_size: 16
val_image_size: 320
train_image_size: 320

mixup_prob: 0.
degrees: 0.
shear: 0.
flip_prob: 0.5
hsv_prob: 1.0
hgain: 5
sgain: 30
vgain: 30
mosaic_scale: [0.5, 1.5]
mosaic_prob: 0.
translate: 0.1
targets_format:
  _target_: super_gradients.training.utils.detection_utils.DetectionTargetsFormat
  value: LABEL_NORMALIZED_CXCYWH
filter_box_candidates: True
