num_joints: 17

# OKs sigma values take from https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py#L523
oks_sigmas: [0.026, 0.025, 0.025, 0.035, 0.035, 0.079, 0.079, 0.072, 0.072, 0.062, 0.062, 1.007, 1.007, 0.087, 0.087, 0.089, 0.089]

edge_links:
  - [0, 1]
  - [0, 2]
  - [1, 2]
  - [1, 3]
  - [2, 4]
  - [3, 5]
  - [4, 6]
  - [5, 6]
  - [5, 7]
  - [5, 11]
  - [6, 8]
  - [6, 12]
  - [7, 9]
  - [8, 10]
  - [11, 12]
  - [11, 13]
  - [12, 14]
  - [13, 15]
  - [14, 16]


train_dataset_params:
  pkl_file: REPLACE_ME_WITH_PATH_TO_TRAIN_DATASET.PKL

val_dataset_params:
  pkl_file: REPLACE_ME_WITH_PATH_TO_VAL_DATASET.PKL

train_dataloader_params:
  shuffle: True
  batch_size: 1024
  num_workers: 0
  drop_last: True

val_dataloader_params:
  batch_size: 1
  num_workers: 0
  drop_last: False

_convert_: all
