defaults:
  - coco_pose_estimation_common_dataset_params
  - _self_

train_dataset_params:
  pkl_file: REPLACE_ME_WITH_PATH_TO_TRAIN_DATASET.PKL

val_dataset_params:
  pkl_file: REPLACE_ME_WITH_PATH_TO_VAL_DATASET.PKL

train_dataloader_params:
  shuffle: True
  batch_size: 1024
  num_workers: 0
  drop_last: True

val_dataloader_params:
  batch_size: 1
  num_workers: 0
  drop_last: False

_convert_: all
