train_dataset_params:
  - _target_: torch.Tensor
      _target_: numpy.zeros
        [4, 3, 320, 320]
  - _target_: torch.LongTensor
      _target_: numpy.zeros
        [4, 6]

train_dataloader_params:
  batch_size: 4
