dataset_dir: /data/Imagenet # path to imagenet directory (local)
img_mean: [0.485, 0.456, 0.406] # mean for normalization
img_std: [0.229, 0.224, 0.225] # std for normalization

aug_repeat_count: 0 # amount of repetitions (each repetition of an example is augmented differently) for a trainset example.

train_dataset_params:
  root: ${dataset_params.dataset_dir}/train
  transform:
    Compose:
      transforms:
        - RandomResizedCropAndInterpolation:
            size: 224 # crop size (size of net's input)
            interpolation: default # interpolation mode
        - RandomHorizontalFlip
        - color_augmentation:
            rand_augment_config_string: # randaugment config string (see super_gradients/training/datasets/auto_augment.py)
            color_jitter: [0., 0., 0.]
            crop_size: 224 # crop size (size of net's input)
            img_mean: ${dataset_params.img_mean}
        - ToTensor
        - Lighting:
            alphastd: 0. # imagenet pca augmentation (applied only to trainset)
        - Normalize:
            mean: ${dataset_params.img_mean}
            std: ${dataset_params.img_std}
        - RandomErase:
            probability: 0. # random erase probability (applied only to trainset)
            value: 0.

val_dataset_params:
  root: ${dataset_params.dataset_dir}/val
  transform:
    Compose:
      transforms:
        - Resize:
            size: 256 # loaded image resize size (appplied first among preprocessing transforms)
        - CenterCrop:
            size: 224 # crop size (size of net's input)
        - ToTensor
        - Normalize:
            mean: ${dataset_params.img_mean}
            std: ${dataset_params.img_std}

train_dataloader_params:
  batch_size: 64
  num_workers: 8
  drop_last: False
  pin_memory: True
  worker_init_fn:
    _target_: super_gradients.training.utils.utils.load_func
    dotpath: super_gradients.training.datasets.datasets_utils.worker_init_reset_seed
#  collate_fn:
#    _target_: torch.utils.data._utils.collate.default_collate

val_dataloader_params:
  batch_size: 200
  num_workers: 8
  drop_last: False
  pin_memory: True
  worker_init_fn:
    _target_: super_gradients.training.utils.utils.load_func
    dotpath: super_gradients.training.datasets.datasets_utils.worker_init_reset_seed
#  collate_fn:
#    _target_: torch.utils.data._utils.collate.default_collate

_convert_: all