defaults:
  - imagenet_dataset_params

train_transform_args:
  interpolation: random
  random_erase_prob: 0.2
  random_erase_value: random
  auto_augment_config_string: rand-m9-mstd0.5

train_dataloader_params:
  drop_last: True
  batch_size: 256

val_dataloader_params:
  batch_size: 256
