defaults:
  - imagenet_dataset_params

train_args:
  drop_last: True
  batch_size: 256
  interpolation: random
  random_erase_prob: 0.2
  random_erase_value: random
  auto_augment_config_string: rand-m9-mstd0.5

val_args:
  batch_size: 256
