defaults:
  - imagenet_dataset_params

resize_size: 249
batch_size: 64
random_erase_prob: 0
random_erase_value: random
train_interpolation: random
config_string: rand-m7-mstd0.5
cutmix: True
cutmix_params:
  mixup_alpha: 0.2
  cutmix_alpha: 1.0
  label_smoothing: 0.1
img_mean: [0.5, 0.5, 0.5]
img_std: [0.5, 0.5, 0.5]


# TODO: REMOVE ABOVE, HERE FOR COMPATIBILITY UNTIL WE REMOVE DATASET_INTERFACE
# TODO: UNCOMMENT BELOW WHEN ABOVE IS REMOVED
#defaults:
#  - imagenet_dataset_params

#img_mean: [0.5, 0.5, 0.5]
#img_std: [0.5, 0.5, 0.5]

train_dataset_params:
  root: /data/Imagenet/train
  transform:
    Compose:
      transforms:
        - RandomResizedCropAndInterpolation:
            size: 224
            interpolation: random
        - RandomHorizontalFlip
        - RandomAugmentation:
            config_str: rand-m7-mstd0.5
            crop_size: 224
            img_mean: ${dataset_params.img_mean}
        - ToTensor
        - Normalize:
            mean: ${dataset_params.img_mean}
            std: ${dataset_params.img_std}

val_dataset_params:
  root: /data/Imagenet/val
  transform:
    Compose:
      transforms:
        - Resize:
            size: 249 # This is changed compared to default
        - CenterCrop:
            size: 224
        - ToTensor
        - Normalize:
            mean: ${dataset_params.img_mean}
            std: ${dataset_params.img_std}

train_dataloader_params:
  batch_size: 64
  collate_fn:
    _target_: super_gradients.training.datasets.mixup.CollateMixup
    mixup_alpha: 0.2
    cutmix_alpha: 1.0
    label_smoothing: 0.1
