# RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

defaults:
  - imagenet_dataset_params

img_mean: [0.5, 0.5, 0.5]
img_std: [0.5, 0.5, 0.5]

train_args:
  batch_size: 64
  interpolation: random
  color_jitter: [0.4, 0.4, 0.4]
  random_erase_prob: 0.
  random_erase_value: random
  auto_augment_config_string: rand-m7-mstd0.5
  collate_fn:
    _target_: super_gradients.training.datasets.mixup.CollateMixup
    mixup_alpha: 0.2
    cutmix_alpha: 1.0
    label_smoothing: 0.1


val_args:
  resize_size: 249
