defaults:
  - imagenet_dataset_params

batch_size: 128

# TODO: REMOVE ABOVE, HERE FOR COMPATIBILITY UNTIL WE REMOVE DATASET_INTERFACE
#defaults:
#  - imagenet_dataset_params

train_dataloader_params:
  batch_size: 128
  num_workers: 16

val_dataloader_params:
  num_workers: 16
