config_version: '1.2'

fill_values:
  '1.2':
    _target_: super_gradients.training.datasets.segmentation_datasets.mapillary.MapillaryDataset.IGNORE_LABEL_V1_2
  '2.0':
    _target_: super_gradients.training.datasets.segmentation_datasets.mapillary.MapillaryDataset.IGNORE_LABEL_V2_0

fill_value: ${choose:${config_version},${fill_values}}

train_dataset_params:
  root: /data/mapillary-vistas-dataset_public_v2.0
  config_file: config_v${..version}.json
  samples_sub_directory: training/images
  targets_sub_directory: training/v${..version}/labels
  cache_labels: False
  cache_images: False
  transforms:
    - SegRescale:
        long_size: 2048

    - SegColorJitter:
        brightness: 0.5
        contrast: 0.5
        saturation: 0.5

    - SegRandomFlip:
        prob: 0.5

    - SegRandomRescale:
        scales: [ 0.5, 2.0 ]

    - SegPadShortToCropSize:
        crop_size: 1024
        fill_mask: ${..fill_value}

    - SegCropImageAndMask:
        crop_size: 1024
        mode: random

val_dataset_params:
  root: /data/mapillary-vistas-dataset_public_v2.0
  config_file: config_v${..version}.json
  samples_sub_directory: validation/images
  targets_sub_directory: validation/v${..version}/labels
  cache_labels: False
  cache_images: False
  transforms:
    - SegRescale:
        long_size: 2048

    - SegToDivisible:
        divisible_value: 32
        fill_mask: ${..fill_value}

    - SegCropImageAndMask:
        crop_size: 512
        mode: center


train_dataloader_params:
  shuffle: True
  batch_size: 4
  num_workers: 8
  drop_last: True
  pin_memory: True

val_dataloader_params:
  batch_size: 1
  num_workers: 8
  drop_last: False
  pin_memory: True
