config_version: '1.2'

fill_values:
  '1.2': 65
  '2.0': 123

fill_value: ${choose:${dataset_params.config_version},${dataset_params.fill_values}}

train_dataset_params:
#  root_dir: /data/mapillary-vistas-dataset_public_v2.0
  root_dir: /home/lior.kadoch/data/mapillary-vistas-dataset_public_v2.0_resize_2048_long
  config_file: config_v${..config_version}.json
  samples_sub_directory: training/images
  targets_sub_directory: training/v${..config_version}/labels
  cache_labels: False
  cache_images: False
  transforms:
    - SegRescale:
        long_size: 2048

    - SegColorJitter:
        brightness: 0.5
        contrast: 0.5
        saturation: 0.5

    - SegRandomFlip:
        prob: 0.5

    - SegRandomRescale:
        scales: [ 0.5, 2.0 ]

    - SegPadShortToCropSize:
        crop_size: 1024
        fill_mask: ${dataset_params.fill_value}

    - SegCropImageAndMask:
        crop_size: 1024
        mode: random

val_dataset_params:
#  root_dir: /data/mapillary-vistas-dataset_public_v2.0
  root_dir: /home/lior.kadoch/data/mapillary-vistas-dataset_public_v2.0_resize_2048_long
  config_file: config_v${..config_version}.json
  samples_sub_directory: validation/images
  targets_sub_directory: validation/v${..config_version}/labels
  cache_labels: False
  cache_images: False
  transforms:
    - SegRescale:
        long_size: 2048

    - SegPadToDivisible:
        divisible_value: 32
        fill_mask: ${dataset_params.fill_value}

    - SegCropImageAndMask:
        crop_size: 512
        mode: center


train_dataloader_params:
  shuffle: True
  batch_size: 4
  num_workers: 8
  drop_last: True
  pin_memory: True

val_dataloader_params:
  batch_size: 1
  num_workers: 8
  drop_last: False
  pin_memory: True
