img_size: 512
crop_size: 512
pascal_ignore_label: 21

train_dataset_params:
  root: /data/pascal_voc_2012
  list_file: VOCdevkit/VOC2012/ImageSets/Segmentation/train.txt
  samples_sub_directory: VOCdevkit/VOC2012/JPEGImages
  targets_sub_directory: VOCdevkit/VOC2012/SegmentationClass
  cache_labels: False
  cache_images: False
  transforms:
    # for more options see common.factories.transforms_factory.py
    - SegRescale:
        long_size: ${img_size}

    - SegRandomFlip:
        prob: 0.5

    - SegColorJitter:
        brightness: 0.5
        contrast: 0.5
        saturation: 0.5

    - SegRandomRescale:
        scales: [ 0.5, 2.0 ]

    - SegPadShortToCropSize:
        crop_size: ${crop_size}
        fill_mask: ${pascal_ignore_label}

    - SegCropImageAndMask:
        crop_size: ${crop_size}
        mode: random

val_dataset_params:
  root: /data/pascal_voc_2012
  list_file: VOCdevkit/VOC2012/ImageSets/Segmentation/val.txt
  samples_sub_directory: VOCdevkit/VOC2012/JPEGImages
  targets_sub_directory: VOCdevkit/VOC2012/SegmentationClass
  cache_labels: False
  cache_images: False
  transforms:
    - SegRescale:
        long_size: ${img_size}

    - SegPadShortToCropSize:
        crop_size: ${crop_size}
        fill_mask: ${pascal_ignore_label}

    - SegCropImageAndMask:
        crop_size: ${crop_size}
        mode: center


train_dataloader_params:
  batch_size: 64
  num_workers: 8
  drop_last: False
  pin_memory: True

val_dataloader_params:
  batch_size: 200
  num_workers: 8
  drop_last: False
  pin_memory: True
