train_dataset_params:
  root_dir: /data/supervisely-persons
  list_file: train.csv
  cache_labels: False
  cache_images: False
  transforms: []
  augment: True

val_dataset_params:
  root_dir: /data/supervisely-persons
  list_file: val.csv
  cache_labels: False
  cache_images: False
  transforms: []
  augment: False

train_dataloader_params:
  batch_size: 8
  drop_last: True                 # drop the last incomplete batch, if dataset size is not divisible by the batch size

val_dataloader_params:
  batch_size: 8
  drop_last: False

_convert_: all