train_dataset_params:
  root: /data/TinyImagenet/train
  transform:
    Compose:
      transforms:
        - RandomResizedCropAndInterpolation:
            size: 56
        - RandomHorizontalFlip
        - ToTensor
        - Normalize:
            mean: [0.4802, 0.4481, 0.3975]
            std: [0.2770, 0.2691, 0.2821]

val_dataset_params:
  root: /data/TinyImagenet/val
  transform:
    Compose:
      transforms:
        - Resize:
            size: 64
        - CenterCrop:
            size: 56
        - ToTensor
        - Normalize:
            mean: [0.4802, 0.4481, 0.3975]
            std: [0.2770, 0.2691, 0.2821]

train_dataloader_params:
  batch_size: 64
  num_workers: 8
  drop_last: False
  pin_memory: True
  worker_init_fn:
    _target_: super_gradients.training.utils.utils.load_func
    dotpath: super_gradients.training.datasets.datasets_utils.worker_init_reset_seed

val_dataloader_params:
  batch_size: 200
  num_workers: 8
  drop_last: False
  pin_memory: True
  worker_init_fn:
    _target_: super_gradients.training.utils.utils.load_func
    dotpath: super_gradients.training.datasets.datasets_utils.worker_init_reset_seed


_convert_: all