defaults:
  - default_train_params

max_epochs: 550
lr_updates:
  _target_: numpy.arange
  start: 0
  stop: 500
  step: 3

lr_mode: step
lr_decay_factor: 0.963
initial_lr: 0.032
optimizer: RMSpropTF

optimizer_params:
  eps: 0.001
  weight_decay: 1e-5

lr_warmup_epochs: 5
loss: cross_entropy
zero_weight_decay_on_bias_and_bn: True
ema: True

loss_logging_items_names: [Loss]
metric_to_watch: Accuracy
greater_metric_to_watch_is_better: True

train_metrics_list:                               # metrics for evaluation
  - _target_: super_gradients.training.metrics.Accuracy
  - _target_: super_gradients.training.metrics.Top5

valid_metrics_list:                               # metrics for evaluation
  - _target_: super_gradients.training.metrics.Accuracy
  - _target_: super_gradients.training.metrics.Top5

_convert_: all
