load_backbone: False # whether to load only backbone part of checkpoint
checkpoint_path: # checkpoint path that is not located in super_gradients/checkpoints
strict_load: # key matching strictness for loading checkpoint's weights
  _target_: super_gradients.training.sg_trainer.StrictLoad
  value: True