# Cifar10 Classification Training:
# Reaches ~94.9 Accuracy after 250 Epochs
# Instructions:
#   0. Make sure that the data is stored in dataset_params.dataset_dir or add "dataset_params.data_dir=<PATH-TO-DATASET>" at the end of the command below (feel free to check ReadMe)
#   1. Move to the project root (where you will find the ReadMe and src folder)
#   2. Run the command:
#       python src/super_gradients/examples/train_from_recipe_example/train_from_recipe.py --config-name=cifar10_resnet +experiment_name=cifar10

defaults:
  - training_hyperparams: cifar10_resnet_train_params
  - dataset_params: cifar10_dataset_params
  - arch_params: resnet18_cifar_arch_params
  - checkpoint_params: default_checkpoint_params

dataset_interface:
  cifar_10:
    dataset_params: ${dataset_params}

data_loader_num_workers: 8

load_checkpoint: False
checkpoint_params:
  load_checkpoint: ${load_checkpoint}

model_checkpoints_location: local
ckpt_root_dir:

sg_model:
  _target_: super_gradients.SgModel
  experiment_name: ${experiment_name}
  model_checkpoints_location: ${model_checkpoints_location}
  multi_gpu: Off

architecture: resnet18_cifar
