#  STDC segmentation training example with Cityscapes dataset.
#  Reproduction and refinement of paper: Rethinking BiSeNet For Real-time Semantic Segmentation.
#
#  Usage STDC1-Seg75:
#      python -m torch.distributed.launch --nproc_per_node=2 train_from_recipe.py --config-name=cityscapes_stdc_seg75_dice_edge checkpoint_params.external_checkpoint_path=<stdc1-backbone-pretrained-path>
#  Usage STDC2-Seg75:
#      python -m torch.distributed.launch --nproc_per_node=2 train_from_recipe.py --config-name=cityscapes_stdc_seg75_dice_edge checkpoint_params.external_checkpoint_path=<stdc2-backbone-pretrained-path> architecture=stdc2_seg
#
#
#  Validation mIoU - Cityscapes, training time:
#      STDC1-Seg75:    input-size: [768, 1536]     mIoU:      2 X RTX A5000, 29 H, early stopped after 711 epochs
#      STDC2-Seg75:    input-size: [768, 1536]     mIoU:      2 X RTX A5000, 29 H, early stopped after 530 epochs
#
#  Official git repo:
#      https://github.com/MichaelFan01/STDC-Seg
#  Paper:
#      https://arxiv.org/abs/2104.13188
#
#  Pretrained checkpoints:
#      Backbones- downloaded from the author's official repo.
#       https://deci-pretrained-models.s3.amazonaws.com/stdc_backbones/stdc1_imagenet_pretrained.pth
#       https://deci-pretrained-models.s3.amazonaws.com/stdc_backbones/stdc2_imagenet_pretrained.pth
#
#      Logs, tensorboards and network checkpoints:
#       STDC1-Seg75: https://deci-pretrained-models.s3.amazonaws.com/stdc1_seg75_cityscapes/
#       STDC2-Seg75: https://deci-pretrained-models.s3.amazonaws.com/stdc2_seg75_cityscapes/
#
#
#  Learning rate and batch size parameters, using 4 GeForce RTX 2080 Ti with DDP:
#      STDC1-Seg75:    input-size: [768, 768]     initial_lr: 0.0075   batch-size: 12 * 2gpus = 24
#      STDC2-Seg75:    input-size: [768, 768]     initial_lr: 0.0075   batch-size: 12 * 2gpus = 24

defaults:
  - cityscapes_stdc_seg50_dice_edge

dataset_params:
  batch_size: 12
  val_batch_size: 12
  crop_size:
    - 768
    - 768
  eval_scale: 0.75
  random_scales: [0.25, 1.75]

training_hyperparams:
  initial_lr: 0.0075

experiment_name: ${architecture}75_cityscapes
