# SSD MobileNetV2 Detection training on CoCo2017 Dataset:
# Trained in 320x320 mAP@0.5@0.95 (COCO API, confidence 0.001, IoU threshold 0.6, test on 320x320 images) ~20.52
# Checkpoint path: https://deci-pretrained-models.s3.amazonaws.com/ssd_lite_mobilenet_v2_coco_res320_new_coco_filtered_affine_scale_5_15_no_mosaic/ckpt_best.pth
# (trained with stride_16_plus_big)
# Hardware: 8 NVIDIA RTX 3090
# Training time: ±17 hours

# Instructions:
# Set the PYTHONPATH environment variable: (Replace "YOUR_LOCAL_PATH" with the path to the downloaded repo):
# export PYTHONPATH="YOUR_LOCAL_PATH"/super_gradients/src:"YOUR_LOCAL_PATH"/super_gradients/
#
# Run with:
# python3 -m torch.distributed.launch --nproc_per_node=8 train_from_recipe.py --config-name=coco2017_ssd_lite_mobilenet_v2.yaml


# NOTE:
# Anchors will be selected based on validation resolution and anchors_name
# To switch between anchors, set anchors_name to something else defined in the anchors section
# e.g.
# python3 -m torch.distributed.launch --nproc_per_node=4 train_from_recipe_example/train_from_recipe.py \
# --config-name=coco_ssd_lite_mobilenet_v2.yaml anchors_name=stride_16_plus


defaults:
  - training_hyperparams: coco2017_ssd_lite_mobilenet_v2_train_params
  - dataset_params: coco_detection_ssd_lite_mobilenet_v2_dataset_params
  - arch_params: default_arch_params
  - checkpoint_params: default_checkpoint_params
  - anchors: ssd_anchors

architecture: ssd_lite_mobilenet_v2

data_loader_num_workers: 8
model_checkpoints_location: local
experiment_suffix: res${dataset_params.val_image_size}
experiment_name: ${architecture}_coco_${experiment_suffix}

sg_model:
  _target_: super_gradients.SgModel
  experiment_name: ${experiment_name}
  model_checkpoints_location: ${model_checkpoints_location}
  multi_gpu: DDP

anchors_resolution: ${dataset_params.val_image_size}x${dataset_params.val_image_size}
anchors_name: stride_16_plus_big
dboxes: ${anchors.${anchors_resolution}.${anchors_name}}

arch_params:
  num_classes: 80
  anchors: ${dboxes}

dataset_interface:
  coco2017_detection:
    dataset_params: ${dataset_params}

training_hyperparams:
  criterion_params:
    alpha: 1.0
    dboxes: ${dboxes}


