defaults:
  - training_hyperparams: coco2017_yolo_nas_pose_train_params
  - dataset_params: coco_pose_estimation_yolo_nas_mosaic_dataset_params
  - arch_params: yolo_nas_pose_s_shared_arch_params
  - checkpoint_params: default_checkpoint_params
  - _self_
  - variable_setup

architecture: yolo_nas_pose_shared_s

multi_gpu: DDP
num_gpus: 8

# Assemble experiment suffix
bbox_cls_loss_suffix: box_${training_hyperparams.criterion_params.classification_loss_type}_${training_hyperparams.criterion_params.classification_loss_weight}
bbox_reg_loss_suffix: ${training_hyperparams.criterion_params.regression_iou_loss_type}_${training_hyperparams.criterion_params.iou_loss_weight}_dfl_${training_hyperparams.criterion_params.dfl_loss_weight}
pose_cls_loss_suffix: pose_${training_hyperparams.criterion_params.pose_classification_loss_type}_${training_hyperparams.criterion_params.pose_cls_loss_weight}
pose_reg_loss_suffix: reg_${training_hyperparams.criterion_params.pose_reg_loss_weight}

head_suffix: ""
experiment_suffix: "ema_less_mosaic_rescale_loss_lr_focal"
experiment_name: coco2017_${architecture}_${bbox_cls_loss_suffix}_${bbox_reg_loss_suffix}_${pose_cls_loss_suffix}_${pose_reg_loss_suffix}_${head_suffix}_${dataset_params.dataset_params_suffix}${experiment_suffix}

ckpt_root_dir:

train_dataloader: coco2017_pose_train
val_dataloader: coco2017_pose_val

arch_params:
  num_classes: ${dataset_params.num_joints}

training_hyperparams:
  # phase_callbacks: [ ] # Disable visualization
  criterion_params:
    classification_loss_type: focal
    pose_classification_loss_type: focal
    rescale_pose_loss_with_assigned_score: True
    pose_reg_loss_weight: 34

  ema: True
  ema_params:
    decay: 0.997
    decay_type: threshold

  initial_lr:  2e-3
  max_epochs: 1000
  cosine_final_lr_ratio: 0.05

  sg_logger: wandb_sg_logger
  sg_logger_params:
    api_server: https://wandb.research.deci.ai
    entity: super-gradients
    launch_tensorboard: false
    monitor_system: true
    project_name: PoseEstimation
    save_checkpoints_remote: true
    save_logs_remote: true
    save_tensorboard_remote: false
    tb_files_user_prompt: false
    tensorboard_port: null


checkpoint_params:
  # For training Yolo-NAS-S pose estimation model we use pretrained weights for Yolo-NAS-S object detection model.
  # By setting strict_load: key_matching we load only those weights that match the keys of the model.
  checkpoint_path: https://sghub.deci.ai/models/yolo_nas_s_coco.pth
  strict_load:
    _target_: super_gradients.training.sg_trainer.StrictLoad
    value: key_matching

dataset_params:
  mosaic_prob: 0.5

  train_dataloader_params:
    batch_size: 48

  val_dataloader_params:
    batch_size: 48
