defaults:
  - training_hyperparams: default_train_params
  - dataset_params: coco_detection_dataset_params
  - arch_params: default_arch_params
  - checkpoint_params: default_checkpoint_params

#checkpoint_params:
#  load_checkpoint: true

architecture: ssd_lite_mobilenet_v2
project_name: SSD_Mobile

dataset_params:
  batch_size: 60
  val_batch_size: 60
  val_image_size: 320
  train_image_size: 320
  labels_offset: 1

# stride_N_plus is for models where the first skip begins from the feature map with output stride N and higher
# grids of [input_size / N x input_size / N] and smaller
anchors:
  256:
    stride_16_plus:
      _target_: super_gradients.training.utils.ssd_utils.DefaultBoxes
      fig_size: 256
      feat_size: [ 32, 16, 8, 4, 2, 1 ]
      scales: [ 18, 38, 84, 131, 177, 223, 269 ]
      aspect_ratios: [ [ 2 ], [ 2, 3 ], [ 2, 3 ], [ 2, 3 ], [ 2 ], [ 2 ] ]
      scale_xy: 0.1
      scale_wh: 0.2
    stride_8_plus: [[2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3]]
  300:
    stride_8_plus:
      _target_: super_gradients.training.utils.ssd_utils.DefaultBoxes
      fig_size: 300
      feat_size: [38, 19, 10, 5, 3, 2]
      scales: [21, 45, 99, 153, 207, 261, 315]
      aspect_ratios: [[2], [2, 3], [2, 3], [2, 3], [2], [2]]
      scale_xy: 0.1
      scale_wh: 0.2
    stride_16_plus:
      _target_: super_gradients.training.utils.ssd_utils.DefaultBoxes
      fig_size: 300
      feat_size: [19, 10, 5, 3, 2, 1]
      scales: [21, 45, 99, 153, 207, 261, 315]
      # scales: [60, 105, 150, 195, 240, 285, 330]
      aspect_ratios: [[2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3]]
      scale_xy: 0.1
      scale_wh: 0.2
  320:
    stride_8_plus:
      _target_: super_gradients.training.utils.ssd_utils.DefaultBoxes
      fig_size: 320
      feat_size: [ 40, 20, 10, 5, 3, 2 ]
      scales: [ 22, 48, 106, 163, 221, 278, 336 ]
      aspect_ratios: [ [ 2 ], [ 2, 3 ], [ 2, 3 ], [ 2, 3 ], [ 2 ], [ 2 ] ]
      scale_xy: 0.1
      scale_wh: 0.2
    stride_16_plus:
      _target_: super_gradients.training.utils.ssd_utils.DefaultBoxes
      fig_size: 320
      feat_size: [ 20, 10, 5, 3, 2, 1 ]
      scales: [ 22, 48,  106, 163, 221, 278, 336 ]
      aspect_ratios: [ [ 2, 3 ], [ 2, 3 ], [ 2, 3 ], [ 2, 3 ], [ 2, 3 ], [ 2, 3 ] ]
      scale_xy: 0.1
      scale_wh: 0.2

data_loader_num_workers: 8
model_checkpoints_location: local
experiment_suffix: batch${dataset_params.batch_size}_lr${training_hyperparams.initial_lr}_res${dataset_params.val_image_size}
experiment_name: ${architecture}_coco_${experiment_suffix}_dboxes_and_warmup_fixed_4gpus

sg_model:
  _target_: super_gradients.SgModel
  experiment_name: ${experiment_name}
  model_checkpoints_location: ${model_checkpoints_location}
  multi_gpu: AUTO

dboxes: # ${anchors.300.stride_8_plus}
  _target_: super_gradients.training.utils.ssd_utils.DefaultBoxes
  fig_size: 320
  feat_size: [ 40, 20, 10, 5, 3, 2 ]
  scales: [ 22, 48, 106, 163, 221, 278, 336 ]
  aspect_ratios: [ [ 2 ], [ 2, 3 ], [ 2, 3 ], [ 2, 3 ], [ 2 ], [ 2 ] ]
  scale_xy: 0.1
  scale_wh: 0.2

arch_params:
  num_classes: 81  # 80 + 1 for the background class

dataset_interface:
  coco2017_detection:
    dataset_params: ${dataset_params}

training_hyperparams:
  max_epochs: 300
  lr_mode: cosine
  cosine_final_lr_ratio: 0.1
  batch_accumulate: 1
  initial_lr: 0.01
  loss: ssd_loss
  loss_logging_items_names: [ smooth_l1, closs, Loss ]
  criterion_params:
    alpha: 1.0
    dboxes: ${dboxes}

  optimizer: SGD
  optimizer_params:
    momentum: 0.9
    weight_decay: 0.0005
    nesterov: True
  lr_warmup_epochs: 3
  warmup_momentum: 0.8
  warmup_initial_lr: 1e-06
  warmup_bias_lr: 0.1
  warmup_mode: yolov5_warmup
#  phase_callbacks:
#    - _target_: super_gradients.training.utils.callbacks.DetectionVisualizationCallback
#      post_prediction_callback:
#        _target_: super_gradients.training.utils.ssd_utils.SSDPostPredictCallback
#        dboxes: ${dboxes}
#        conf: 0.25
#        iou: 0.45

  valid_metrics_list:
    - _target_: super_gradients.training.metrics.DetectionMetrics
      post_prediction_callback:
        _target_: super_gradients.training.utils.ssd_utils.SSDPostPredictCallback
        dboxes: ${dboxes}
        conf: 0.001
        iou: 0.6
      num_cls: 80

  metric_to_watch: 'mAP@0.50:0.95'
  greater_metric_to_watch_is_better: True

