# Custom recipe to train YoloX on DocLayNet dataset

defaults:
  - training_hyperparams: coco2017_yolox_train_params
  - dataset_params: coco_detection_dataset_params
  - checkpoint_params: default_checkpoint_params
  - _self_
  - variable_setup

arch_params:
  num_classes: 11

checkpoint_params:
  load_checkpoint: True
  checkpoint_path: /mnt/ml-team/homes/marianna.parzych/Unstructured/super-gradients-fork/checkpoints/training_512x512/RUN_20240120_141334_742570/ckpt_best.pth

# num_classes of checkpoint_path/ pretrained_weights, when checkpoint_path is not None.
# Used when num_classes != checkpoint_num_class.
# In this case, the module will be initialized with checkpoint_num_class, then weights will be loaded.
# Finally model.replace_head(new_num_classes=num_classes) is called to replace the head with new_num_classes.
checkpoint_num_classes: 11 # number of classes in the checkpoint

dataset_params:
  val_dataset_params:
    data_dir: /mnt/ml-team/homes/marianna.parzych/Unstructured/MiniHolistic
    images_dir: PNG
    json_file: COCO/test_doclaynet_classes.json
    transforms:
      - DetectionPaddedRescale:
          input_dim: [512, 512] 
      - DetectionTargetsFormatTransform:
          input_dim: [512, 512] 
          output_format: LABEL_CXCYWH

  val_dataloader_params:
    dataset: DocLayNetDetectionDataset
    batch_size: 4
    num_workers: 4

# resume: False
# training_hyperparams:
#   resume: ${resume}
#   max_epochs: 100
#   criterion_params:
#     num_classes: ${arch_params.num_classes}

architecture: yolox_l

experiment_name: evaluation_test
