# TODO: PRODUCE RESULTS AND ADD TENSORBOARDS, LOGS, TRAINING TIME ETC.

defaults:
  - training_hyperparams: imagenet_mobilenetv3_train_params
  - dataset_params: imagenet_mobilenetv3_dataset_params
  - checkpoint_params: default_checkpoint_params

model_checkpoints_location: local
load_checkpoint: False
checkpoint_params:
  load_checkpoint: ${load_checkpoint}

experiment_name: mobileNetv3_large_training

ckpt_root_dir:

multi_gpu:
  _target_: super_gradients.training.sg_trainer.MultiGPUMode
  value: 'DDP'

architecture: mobilenet_v3_large
