# Custom recipe to train PPYoloE on DocLayNet dataset

defaults:
  - training_hyperparams: coco2017_ppyoloe_train_params
  - dataset_params: coco_detection_ppyoloe_dataset_params
  - arch_params: ppyoloe_l_arch_params
  - checkpoint_params: default_checkpoint_params
  - _self_
  - variable_setup

arch_params:
  num_classes: 11

checkpoint_params:
  load_checkpoint: True
  pretrained_weights: coco

# num_classes of checkpoint_path/ pretrained_weights, when checkpoint_path is not None.
# Used when num_classes != checkpoint_num_class.
# In this case, the module will be initialized with checkpoint_num_class, then weights will be loaded.
# Finally model.replace_head(new_num_classes=num_classes) is called to replace the head with new_num_classes.
checkpoint_num_classes: # number of classes in the checkpoint

train_dataloader: coco2017_train_ppyoloe
val_dataloader: coco2017_val_ppyoloe

dataset_params:
  train_dataset_params:
    data_dir: /path/to/DocLayNet # Where the data is stored.
    subdir: PNG
    json_file: COCO/train.json # Local path to json annotation file todo train.json
    all_classes_list: [ Caption, Footnote, Formula, List-item, Page-footer, Page-header, Picture, Section-header, Table, Text, Title,] # List of classes used in your dataset.
    input_dim: [1025, 1025]
    transforms:
      - DetectionRescale:  # todo aspect ratio!
          output_shape: [512, 512]
      - DetectionNormalize:
          mean: [ 123.675, 116.28, 103.53 ]
          std: [ 58.395,  57.12,  57.375 ]
      - DetectionTargetsFormatTransform:
          output_format: LABEL_CXCYWH

  train_dataloader_params:
    batch_size: 4
    num_workers: 4

  val_dataset_params:
    data_dir: /path/to/DocLayNet
    subdir: PNG
    json_file: COCO/val.json
    transforms:
      - DetectionRescale:  # todo aspect ratio!
          output_shape: [512, 512]
      - DetectionNormalize:
          mean: [ 123.675, 116.28, 103.53 ]
          std: [ 58.395,  57.12,  57.375 ]
      - DetectionTargetsFormatTransform:
          output_format: LABEL_CXCYWH

  val_dataloader_params:
    batch_size: 4
    num_workers: 4

resume: False
training_hyperparams:
  resume: ${resume}
  max_epochs: 100
  criterion_params:
    num_classes: ${arch_params.num_classes}

architecture: ppyoloe_l

experiment_name: training_test_ppyoloe
