# Custom recipe to train YoloX on DocLayNet dataset

defaults:
  - training_hyperparams: coco2017_yolox_train_params
  - dataset_params: coco_detection_dataset_params
  - checkpoint_params: default_checkpoint_params
  - _self_
  - variable_setup

arch_params:
  num_classes: 11

checkpoint_params:
  load_checkpoint: True
  pretrained_weights: coco

# num_classes of checkpoint_path/ pretrained_weights, when checkpoint_path is not None.
# Used when num_classes != checkpoint_num_class.
# In this case, the module will be initialized with checkpoint_num_class, then weights will be loaded.
# Finally model.replace_head(new_num_classes=num_classes) is called to replace the head with new_num_classes.
checkpoint_num_classes: # number of classes in the checkpoint

dataset_params:
  train_dataset_params:
    data_dir: /path/to/DocLayNet # Where the data is stored.
    images_dir: PNG # Local path to directory that includes all the images. Path relative to `data_dir`. Can be the same as `labels_dir`.
    json_file: COCO/train.json # Local path to json annotation file
    all_classes_list: [ Caption, Footnote, Formula, List-item, Page-footer, Page-header, Picture, Section-header, Table, Text, Title,] # List of classes used in your dataset.
    input_dim: [1025, 1025]
    transforms:
      - DetectionPaddedRescale:
          input_dim: [512, 512] # Change for different training resolutions (multiplications of 32)
      - DetectionTargetsFormatTransform:
          input_dim: [512, 512] 
          output_format: LABEL_CXCYWH

  train_dataloader_params:
    dataset: DocLayNetDetectionDataset
    batch_size: 4
    num_workers: 4

  val_dataset_params:
    data_dir: /path/to/DocLayNet
    images_dir: PNG
    json_file: COCO/val.json
    transforms:
      - DetectionPaddedRescale:
          input_dim: [512, 512] 
      - DetectionTargetsFormatTransform:
          input_dim: [512, 512] 
          output_format: LABEL_CXCYWH

  val_dataloader_params:
    dataset: DocLayNetDetectionDataset
    batch_size: 4
    num_workers: 4

resume: False
training_hyperparams:
  resume: ${resume}
  max_epochs: 100
  criterion_params:
    num_classes: ${arch_params.num_classes}
  - DetectionMetrics:
        num_cls: ${arch_params.num_classes}
        include_classwise_ap: true
        class_names: ${dataset_params.train_dataset_params.all_classes_list}

architecture: yolox_l

experiment_name: training_test_doclaynet
