ARG BASE_TAG
ARG BASE_DOCKER_REPO
FROM ${BASE_DOCKER_REPO:-307629990626.dkr.ecr.us-east-1.amazonaws.com/deci/super-gradients}:${BASE_TAG:-latest}
LABEL maintainer "DECI.AI <services@deci.ai>"
ARG DEBIAN_FRONTEND=noninteractive
WORKDIR /SG
RUN rm -rf ./
COPY . .
RUN pip install . --no-cache-dir && pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 --extra-index-url https://download.pytorch.org/whl/cu113 --no-cache-dir

CMD bash