name: 'Ci Release Trigger'

on:
  release:
    types: [ published ]

  workflow_dispatch:


jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Circle CI
        id: trigger_circle_ci
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0
        env:
          CCI_TOKEN: ${{ secrets.CIRCLE_CI_TOKEN }}